stages:
    - build
    - test

variables:
    test: "LetsGetMotivated.Tests"

before_script:
    - "dotnet restore"

build:
    stage: build
    script:
        - "cd LetsGetMotivated"
        - "dotnet build"

test:
    stage: test
    script: 
        - "dir"
        - "cd LetsGetMotivated.Test"
        - "dotnet test"