version: '3.5'

networks:
  letsgetmotivatedapi-dev:
    driver: bridge 

services:
  letsgetmotivatedapi:
    image: letsgetmotivatedapi:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=plannerdb;username=planneruser;password=planneruser"
    networks:
      - letsgetmotivatedapi-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "planneruser"
      POSTGRES_PASSWORD: "planneruser"
      POSTGRES_DB: "plannerdb"
    networks:
      - letsgetmotivatedapi-dev
volumes:
  db_volume: